# Generated by Django 6.0.5 on 2026-05-29 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fit_score", models.FloatField(blank=True, null=True)),
                ("interview_prob", models.FloatField(blank=True, null=True)),
                ("skill_gaps", models.JSONField(default=list)),
                ("shap_values", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_result",
                        to="applications.application",
                    ),
                ),
            ],
        ),
    ]
