# Generated by Django 6.0.5 on 2026-05-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_mlresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlresult",
            name="suggestions",
            field=models.JSONField(default=list),
        ),
    ]
